# Generated by Django 5.2.5 on 2025-08-27 17:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Nova'), ('read', 'Lida'), ('replied', 'Respondida'), ('closed', 'Fechada')], default='new', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Gráfica Express', max_length=100)),
                ('site_description', models.TextField(default='Conectando clientes às melhores gráficas')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Percentual padrão de comissão', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('default_production_days', models.IntegerField(default=3, help_text='Dias úteis padrão para produção')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('29.90'), help_text='Valor mínimo para pedidos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('contact_email', models.EmailField(default='contato@graficaexpress.com.br', max_length=254)),
                ('contact_phone', models.CharField(default='(11) 99999-9999', max_length=15)),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
